
Neos:
  Flow:
    mvc:
      routes:
        'Neos.Neos':
          variables:
            # We prefer URLs without the ".html" suffix
            defaultUriSuffix: ''
  Neos:
    eventLog:
      enabled: true
    userInterface:
      navigateComponent:
        nodeTree:
          # number of levels inside the node tree which shall be loaded eagerly, at start.
          # if you have lots of nodes you should maybe reduce this number of elements.
          loadingDepth: 2
        structureTree:
          loadingDepth: 2
      translation:
        autoInclude:
          WG.Site: ['NodeTypes/*']
      editPreviewModes:
        iphone:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'iPhone'
          position: 100
          width: 375px
          height: 667px
          backgroundColor: 'black'
        ipad:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'iPad - landscape'
          position: 100
          width: 1024px
          height: 768px
          backgroundColor: 'black'
    fusion:
      autoInclude:
        WG.Site: true
    # nodeTypes:
    #   groups:
    #     contentBlocks:
    #       position: 110
    #       label: 'Content Blocks'
    Ui:
      frontendConfiguration:
        hotkeys: ~
      initialState:
        ui:
          leftSideBar:
            contentTree:
              # by default in the Neos UI open the content tree
              isHidden: false
Carbon:
  Link:
    defaultPhoneCountryCode: '0049'
