Neos:
  Flow:
    i18n:
      defaultLocale: de
      fallbackRule:
        order: ['en']
  ContentRepository:
    contentDimensions:
      language:
        label: Languages
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          de:
            label: DE
            values:
              - de
            uriSegment: 'de'
          en:
           label: EN
           values:
              - en
           uriSegment: 'en'
  Neos:
    userInterface:
      defaultLanguage: de
      translation:
        autoInclude:
          WG.Site:
            - Main
            - "NodeTypes/*"
