Neos:
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: ''
        port: '465'
        encryption: 'ssl'
        username: ''
        password: ''
        localDomain: ''
