Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'TechDivision.CkStyles:Styles':
            resource: resource://TechDivision.CkStyles/Public/JavaScript/CkStyles/Plugin.js
      frontendConfiguration:
        'TechDivision.CkStyles:InlineStyles': '${Configuration.setting(''TechDivision.CkStyles.InlineStyles'')}'
        'TechDivision.CkStyles:BlockStyles': '${Configuration.setting(''TechDivision.CkStyles.BlockStyles'')}'


# Achtung!!! Die Definierten Klassen müssen in der CSS Datei definiert sein!!!
TechDivision:
 CkStyles:
  BlockStyles:
    presets:
      'textAlign':
        label: 'Text Ausrichtung'
        options:
          'left':
            label: 'Text links'
            cssClass: 'text-left'
          'middle':
            label: 'Text mittig'
            cssClass: 'text-center'   
          'right':
            label: 'Text rechts'
            cssClass: 'text-right'
